### ISSUE TITLE
Make dev container setup a more complete development environment

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/research-template#104]
This was discussed in #102 when adding initial dev container support for testing.

We could envisage having an entirely self-contained development environment for users who do not want to install OpenSAFELY tooling by hand. It reduces the installation process to:

1. Install Docker
2. Install Visual Studio Code
3. Clone a research repository
4. Open the research repository in Visual Studio Code, and build a dev container from the configuration.

This also could be used in Codespaces for users unable to install the OpenSAFELY tooling themselves.

The other advantage of this is it *should*[^1] be the same setup cross-platform, whether Windows/macOS/Linux/Codespaces.

***

For R, @remlapmot had [built a working R-in-dev-container-setup](https://github.com/opensafely/research-template/pull/102#issuecomment-1629339277), based on the OpenSAFELY R image.

Stata might be more of a problem.

[^1]: Assuming there are no behavioural quirks per platform, which is far from certain.

**Comment by remlapmot** [comment]
For Stata, one suggestion for interactive development could be to launch the `xstata-mp` executable (instead of `stata-mp`). That provides the familiar Stata graphical environment on Linux, which includes the Do-file editor and other windows. Here's a screenshot of it (running from WSL2, I guess WSLg is sorting out the windows - maybe macOS users would need XQuartz installed).

<img width="847" alt="Screenshot 2023-07-12 211952" src="https://github.com/opensafely/research-template/assets/3777473/6f3b02ba-8c58-40b2-86cd-d006f4ebf964">

Also Stata integration with Python is much better than compared with R, since Stata Corp. provide their official pystata Python package <https://www.stata.com/python/>

And there are several Jupyter kernels for Stata - I lost track of which is best/most reliable
* <https://kylebarron.dev/stata_kernel/>
* <https://hugetim.github.io/nbstata/user_guide.html>

**Comment by StevenMaude** [comment]
Running the Stata GUI does remind me of this, which was something I found when searching around:

https://web.archive.org/web/20230320153217/https://technology.amis.nl/software-development/run-and-access-gui-inside-vs-code-devcontainers/

That's working locally and using a local VNC client to access the Flexbox GUI, I think.

It looks like it might be possible to access the Codespaces VNC entirely in browser too:

* blog post: https://dev.to/lowlighter/using-github-codespaces-with-vncflexbox-to-create-pokemon-maps-from-a-web-browser-3ch6 
* code: https://github.com/lowlighter/gracidea/tree/1dd01219b568b81e6a9af975b8f5d08425ac0bb8/.devcontainer

I haven't looked in detail at how this works. It's using https://github.com/novnc/noVNC

**Comment by remlapmot** [comment]
Those look promising.

I had a look in the stata-mp image - I guess you were saving space as it only contains the `stata-mp` binary, i.e., it's missing the `xstata-mp` and other binaries. So you're going to have to add that into the image.

<img width="1003" alt="Screenshot 2023-07-13 at 15 25 05" src="https://github.com/opensafely/research-template/assets/3777473/4548639c-6c1f-41df-8d6e-69a193faf274">

A normal Stata directory on Linux after installation looks like the following (i.e., contains binaries for all Stata flavours, `stata`, `stata-se`, `stata-mp` and their X11 counterparts - screenshot from my install on WSL).

<img width="379" alt="Screenshot 2023-07-13 094702" src="https://github.com/opensafely/research-template/assets/3777473/9a4408a4-144c-4cd0-91fa-98114a5a3cb4">

**Comment by remlapmot** [comment]
Another Linux GUI app I sometimes use and that you could consider including is GitHub Desktop. The Linux version of this is unofficial, but maintained by a GitHub employee (he might even be on the GitHub Desktop team)

<https://github.com/shiftkey/desktop>

The binary is `github-desktop` (screenshot of it running from Ubuntu on WSL).

<img width="799" alt="Screenshot 2023-07-18 202240" src="https://github.com/opensafely/research-template/assets/3777473/b8a0fb8f-a68e-4435-a77c-24bcd00c5345">

The issue to be aware about with this is that to use this with the opensafely GitHub organisation, you would have to grant each user permission to do so. See the known issue 
<https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization>
, which would be a slight inconvenience, but not too bad (or maybe there's a preferable Git/GitHub extension in VSCode).

**Comment by StevenMaude** [comment]
I've not tested Git from within a remote container. But having some way — whether GitHub Desktop or some other option — of working with Git that's not the command line would be something that we probably should get to work.

There are VSCode extensions for this purpose: https://code.visualstudio.com/docs/sourcecontrol/github

I've never used GitHub Desktop, so I don't quite know if those kinds of extensions do encompass all the features of GitHub Desktop that are used.

Though, looking at [the description of GitHub Desktop](https://docs.github.com/en/desktop):

> You can use GitHub Desktop to complete most Git commands from your desktop, such as pushing to, pulling from, and cloning remote repositories, attributing commits, and creating pull requests, with visual confirmation of changes.

It does look like the VSCode extensions do a lot of that, if not all, perhaps? I haven't used the GitHub extension, but it has some quite nice features (like autocompletion of issue/username when editing code).

(In Codespaces, the VSCode Source Control panel magically just works for pushing commits, with your account already authenticated.)

**Comment by remlapmot** [comment]
GitHub Desktop is pretty much the most user friendly Git GUI I've used, I only relatively rarely need `git` command line incantations (but VSCode Source Control pane good too).

It seems VSCode/devcontainers/VSCode Source Code pane looks for whether Git is installed in the container on startup, as I got a warning pop-up about Git not being on PATH when using the r image in the devcontainer.

**Comment by remlapmot** [comment]
I had a go using desktop-lite and managed to get GitHub Desktop, RStudio Desktop, and Stata 17 (`xstata-mp`) running.

My demo repo is <https://github.com/remlapmot/os-test-desktop-lite>

(Note that I haven't committed my Stata installation .tar.gz file nor the UoB Stata license into the repo, so if you run the repo first comment out the last part of the Dockerfile, or I can email you those files if you want to try it.)

Screenshots

<img width="1263" alt="fluxbox-github-desktop" src="https://github.com/opensafely/research-template/assets/3777473/c4337d5e-f7a0-4303-b2a1-a1c79e2d8940">

<img width="1259" alt="fluxbox-rstudio-desktop" src="https://github.com/opensafely/research-template/assets/3777473/c18051dd-4d31-42eb-997b-10fc3aa1421a">

<img width="1447" alt="fluxbox-xstata-mp" src="https://github.com/opensafely/research-template/assets/3777473/16be7473-f254-4ef0-9748-eb261d896405">


Things I found out

* Compared to the blogpost and links Microsoft seem to have very slightly updated syntax, see <https://github.com/devcontainers/features/blob/main/src/desktop-lite/README.md>
* As suggested in that README I had to increase the shared memory, see [here](https://github.com/devcontainers/features/blob/main/src/desktop-lite/README.md#resolving-crashes)
* To save files in the desktop environment back into the repo the directory path in the devcontainer is `/workspaces/{repo-name}` so `/workspaces/os-test-desktop-lite` for my repo
* I had to use Stata 17, as UoB only have that license (and I don't have the installation .tar.gz for Stata 16).
* Stata 17 requires additional system dependencies `linbncurses5` and `libgtk2.0-dev`. I'm not sure if Stata 16 would need the same or earlier versions (or different libraries). It's worth noting that Stata 18 has been out for a few months (Stata usually release a new version about once every 2 years).

**Comment by StevenMaude** [comment]
@remlapmot: that looks very, very promising, and you beat me to looking at this more! [^1] 

Appreciate you having a dig around here, the details of what you've found and sharing your work so far.

I'll see if I can have a proper try of this later this week. I've only skimmed through your repository. One thing I think I learned is that the desktop-lite feature has the VNC client built in, I think, which saves a little bit of wrangling. I didn't realise that before.

There's still the matter of ensuring that the correct versions of R and Stata software and packages get installed as run inside the OpenSAFELY Docker image. But I don't think that's an intractable problem; it is very promising! :smiley:

I do think there's something exciting to build on here. (I can't promise anything, because I'm not officially working on this. But I'll raise it again with other OpenSAFELY developers at Bennett. My *personal* view is that having an easy-to-run and self-contained environment which sets up most of the tooling OpenSAFELY users need cross-platform is a big usability improvement.)

***

More specific things:

> (Note that I haven't committed my Stata installation .tar.gz file nor the UoB Stata license into the repo, so if you run the repo first comment out the last part of the Dockerfile, or I can email you those files if you want to try it.)

Understood! I'll see if I can wrangle our version of Stata to work.

> To save files in the desktop environment back into the repo the directory path in the devcontainer is `/workspaces/{repo-name}` so `/workspaces/os-test-desktop-lite` for my repo

Yes, I think this is standard, from my limited experience of dev containers so far.

> It's worth noting that Stata 18 has been out for a few months (Stata usually release a new version about once every 2 years).

I think updating Stata has been discussed in passing, but I'm not sure the outcome of this or what the plans for this are.

[^1]: In the meantime, I have been [documenting Codespaces more](https://docs.opensafely.org/github-codespaces/).

**Comment by remlapmot** [comment]
Yes, Microsoft or whoever it is has made the desktop-lite setup very easy.

I agree this would be helpful, especially for those users (e.g., at Uni of Leicester) whose computers are very locked down and it's a hassle for them to get the required programs installed from their IT departments.

For the R version I have amended my repo. It now has R 4.0.5 and the same packages at the same versions (with the exception of 2 packages; testhat and rgeos, which I couldn't get those relatively old versions to build on jammy) as the r image (they build on fossa, so I could go back to that).

<img width="901" alt="fluxbox-rstudio-desktop" src="https://github.com/opensafely/research-template/assets/3777473/59ee06cb-a224-448a-8eea-b1bfdf964709">

**Comment by StevenMaude** [comment]
I submitted a draft proposal this week for allocating some development time at Bennett to working on this idea.

Things might be a little slow on this since its the summer holidays too, but I'll update when I know more.

**Comment by remlapmot** [comment]
Ok, that's great.

I tried rebuilding my test repo using Focal (given that the r image is on Focal). My amended Dockerfile builds successfully (`devel` branch of my repo) but for some reason the noVNC connection fails - I don't know why. 
![Screenshot 2023-07-30 202048-crop](https://github.com/opensafely/research-template/assets/3777473/19740e63-9a3a-403f-b9b4-b643c810ea7c)
So my recommendation is to build on Jammy.
