### ISSUE TITLE
RStudio preferences file not always correctly populated on startup

### ISSUE THREAD

**Issue by Jongmassey** [opensafely/research-template#130]
We wish to configure RStudio such that the working directory presented to a user is the "workspace directory" where all there research code assets are. This requires setting the `R` default working directory (for the R console) and the RStudio default working directory for the GUI file browser.

In the dev container configuration, we set the `postCreateCommand` attribute to be a call to `postCreate.sh`. [Within this script](https://github.com/opensafely/research-template/blob/main/.devcontainer/postCreate.sh#L9-L10), we parse the `~/.config/rstudio/rstudio-prefs.json` file using `jq` and add an "initial_working_directory" key with a value of the workspace folder and write this back to the json file. In most cases, this adequately set the RStudio default working directory. 

However, based on [feedback](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1716892511090679) from @alschaffer there appear to be occasions when this setting is not correct when RStudio is opened. This has also been seen by @StevenMaude but not reliably replicated. We suspect that `rstudio-prefs.json` is empty at the time this script runs and so the call to `jq` returns an empty string. 

We presume that the `postCreateCommand` is called before `postAttachCommand` (where RStudio Server is started), but there may be some timing issues or race condition here which would explain the sporadic appearance of this bug.

It is possible to [alter the script](https://github.com/opensafely/research-template/pull/128) to more gracefully handle an empty `rstudio-prefs.json` but without understanding how this bug appears it may not prove as reliable as hoped.

**Comment by Jongmassey** [comment]
The [docs ](https://containers.dev/implementors/json_reference/#lifecycle-scripts) for  dev containers lifecycle scripts state that the
`postCreateCommand` is 

>the last of three that finalizes container setup when a dev container is created. It happens after updateContentCommand and once the dev container has been assigned to a user for the first time.

and

`postAttachCommand `  is

>A command to run each time a tool has successfully attached to the container.

which doesn't immediately strike me as guaranteeing the latter is always executed after the former has finished

**Comment by Jongmassey** [comment]
There is also some documentation about [parallel execution](https://containers.dev/implementors/spec/#parallel-exec) but I'm not sure it applies here.

**Comment by Jongmassey** [comment]
On a fresh pull of the template, run directly with docker

```sh
$ docker image pull ghcr.io/opensafely-core/research-template
[...]
Status: Downloaded newer image for ghcr.io/opensafely-core/research-template:latest
ghcr.io/opensafely-core/research-template:latest
~$ docker run -i -t ghcr.io/opensafely-core/research-template /bin/bash
```

The file is populated, not blank.

```sh
(venv) rstudio@97bcb2401b9d:~$ cat ~/.config/rstudio/rstudio-prefs.json
{
    "save_workspace": "never",
    "always_save_history": false,
    "reuse_sessions_for_project_links": true,
    "posix_terminal_shell": "bash"
}
```

**Comment by Jongmassey** [comment]
AFAICT there are four possible states that could cause the RStudio initial working directory to not be set to the workspace:

* blank config file
* corrupted config file
* config file is populated with stock config (our modification didn't work)
* config file is correctly modified but not picked up by RStudio for some reason

Ideally we'd be able to inspect a codespace displaying this behaviour to see what the state of the config file is. I've asked Andrea on Slack if I can have a look at hers.

**Comment by Jongmassey** [comment]
Just confirmed on a call with @alschaffer  that the preferences file is indeed empty:

```json
{}
```

**Comment by StevenMaude** [comment]
If it helps, I saw there's also a `waitFor` setting which I think could be changed to `postCreateCommand`, but that also has a [potential quirk with Codespaces](https://github.com/orgs/community/discussions/9644) (documented back in 2022, not sure if fixed).

**Comment by lucyb** [comment]
We're going to add this into the troubleshooting guide rather than fixing it as part of this initiative.
