### ISSUE TITLE
Remove repository name from workspace folder path

### ISSUE THREAD

**Issue by Jongmassey** [opensafely/research-template#133]
[research-template ADR#3](https://github.com/opensafely-core/research-template-docker/blob/main/docs/adr/0003-use-of-devcontainer-directory.md) states:

> One element of the dev container configuration which cannot easily be set in the docker image build is that of setting working directories for R/RStudio to the [workspace folder](https://containers.dev/implementors/json_reference/#variables-in-devcontainerjson) which is (by default) not known until container creation time.

This is because we are using the default workspace folder pattern of `/workspace/{repo_name}`.

The setting of the RStudio working directory in the onCreate command is [known to be problematic](https://github.com/opensafely/research-template/issues/130).

It is possible to set the `workspaceFolder` property of `devcontainer.json` [to a fixed value](https://code.visualstudio.com/remote/advancedcontainers/change-default-source-mount), such that it can be known at docker image build time, and those working directory preferences can be set at docker image build time.

With this, we could remove the problematic R setting lines from the `postCreate.sh` script.

One potential downside is that the user will no longer see the repository name in either the file explorer pane or the terminal and so will no longer have immediate visibility of which repository a given codespace pertains to.

I have tried this setting in [a draft PR](https://github.com/opensafely/research-template/pull/132) and it appears to work as stated.

**Comment by iaindillingham** [comment]
We talked about this issue in today's standup. I think we agreed that from a technical perspective, using a fixed working directory is a great idea. However, from a user perspective, context is important: the repository and branch should be displayed somewhere in the UI. Whilst we would normally lean on a Git integration for this (RStudio's version control feature; VS Code's source control feature), RStudio makes this hard (opensafely-core/research-template-docker#48).

Before implementing a fixed working directory, we should identify how a user would know which repository and branch a Codespace is associated with. Users can have up to three Codespaces, and following the "[Co-Piloting in Codespaces](https://drive.google.com/drive/folders/15HCpI8dyHIyiYavX_j7JJVZRnFEiEc1x)" meeting, we should assume that they will make use of them, either associated with different repositories, or different branches within the same repository.

Thanks for describing the issue clearly, @Jongmassey.

**Comment by lucyb** [comment]
We've decided not to fix this for now, but will add something into the troubleshooting guide.

**Comment by iaindillingham** [comment]
Unless I've misunderstood, I don't think we need to add an entry to the troubleshooting guide, because we're not going to remove the repository name from the workspace directory name, and so the repository name will be visible in the UI.

**Comment by Jongmassey** [comment]
I think it's #130  that needs to go in the troubleshooting guide, not this as we're not going to make this change
