### ISSUE TITLE
The dev container .gitignore file is confusing

### ISSUE THREAD

**Issue by lucyb** [opensafely/research-template#135]
When we've been getting user feedback for Codespaces, and our updated dev container configuration, we've found on two or three occasions that researchers have had difficulty with their .gitignore file.

We're currently asking people to [manually copy](https://docs.opensafely.org/getting-started/how-to/add-github-codespaces-to-your-project/#copy-files) the files in the .devcontainer directory from opensafely/research-template to their repo. However, when downloading dotfiles, GitHub removes the leading "." and on some platforms/browsers appends ".txt" (Windows/Edge). We've added some instructions for researchers to follow to correct this, but we believe there's still the potential for confusion.

An easier solution might be for us to move the contents of the .devcontainers/.gitignore into the root .gitignore and to ask people to update that instead.

We originally added a .gitignore into the .devcontainers directory so that we could keep all dev container related changes in a single location. We thought this would make scripting updates easier and mean that the Codespaces configuration isn't affecting the rest of the code base. However, that seems to have come with an unexpected overhead for manually copying things.

Acceptance criteria:
* Update the root .gitignore file and remove the .devcontainer/.gitignore.
* Documentation is updated to include new instructions for adding a Codespace into an existing project
* Update the troubleshooting guide

**Comment by StevenMaude** [comment]
- [ ] #136
- [ ] https://github.com/opensafely/documentation/pull/1545

**Comment by StevenMaude** [comment]
Note: a troubleshooting guide hasn't been yet added.
