### ISSUE TITLE
Roadmap link is broken

### ISSUE THREAD

**Issue by kevfrost** [opensafely/research-template#20]
Link at bottom of Readme.md brings 404 error

**Comment by iaindillingham** [comment]
There are five links currently in _README.md_:

1. An empty link to the paper, which should be added by the study developer.
2. A link to the study definition ✅ 
3. A link to the codelists ✅ 
4. A link to the OpenSAFELY documentation ✅ 
5. A link to the OpenSAFELY website ✅ 

As these aren't broken (now) I'm going to mark this issue as closed. Thank you for reporting, @kevfrost.
