### ISSUE TITLE
Python model example

### ISSUE THREAD

**Issue by marcus-clements** [opensafely/research-template#23]
I had a look around the OpenSAFELY repos but I couldn't find an example of a Python model so I had a go at creating a project from this template which does execute a (toy) Python model

https://github.com/marcus-clements/opensafely-project-python-example

Seems to work fine on the dummy data generated by the cohort extractor.

I'd be happy to fork and make a PR if it's useful for others.

**Comment by iaindillingham** [comment]
Thanks for the example @marcus-clements, which shows how to compute the pairwise correlation of columns within a Pandas data frame. There are many Python libraries that we might use to model relationships within the data; our [`python-docker`](https://github.com/opensafely-core/python-docker) image comes with [scipy](https://www.scipy.org/scipylib/index.html) and [scikit-learn](https://scikit-learn.org/stable/), for example. However, there isn't a standard approach: Pandas has several data frame methods that model the data; scikit-learn provides both functional and object-oriented approaches, using [pipelines](https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html#building-a-pipeline). Consequently, adding a general example to the documentation would be hard. Hopefully the documentation on [scripted actions](https://docs.opensafely.org/actions-scripts/) and [the project pipeline](https://docs.opensafely.org/actions-pipelines/) are sufficient.

Please do consider opening a PR on [the OpenSAFELY documentation](https://github.com/opensafely/documentation), though, if you feel a specific use case is missing.
