### ISSUE TITLE
Polish Gitpod configuration for users

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/research-template#37]
Documenting things and updating as I'm using it; these may or may not be important issues:

Repository created from commit 68861b9 of this template:

- [ ] for the "Update opensafely" terminal window (window 2), on first launch of the Workspace, get an error: `bash: opensafely: command not found` for `opensafely upgrade`
- [ ] default layout (bottom-right) is `Layout: us`, not sure what the impact of this is.
- [ ] Python extension window pops up when opening a Python file (probably for first time).
- [ ] menu bar isn't enabled, but this has issues in Firefox (for a maximised window, the menu bar disappeared entirely!). Could open a issue with Gitpod for this.
- [ ] Via @iaindillingham: "Unfortunately, the Gitpod UI for creating a PR is broken on Safari"
- [ ] Underscores can't been seen in the terminal in Firefox
- [ ] Via @andrewscolm: not possible to preview HTML easily

**Comment by iaindillingham** [comment]
I think the pre-build swallows errors, but the workspace still opens. For example, when my sro-measures-demo study included a *.python-version* file that wasn't equal to the Gitpod Python version, the pre-build failed, but the workspace still opened.

I think the default US keyboard layout will mean folks with an ISO keyboard layout might have to hunt around for the backslash (<kbd>\\</kbd>).

There are a few non-Chrome surprises. For example, the Data Preview extension doesn't work on first-open in Firefox and, as noted, the "Create Pull Request" form doesn't work on Safari. But Gitpod is such an improvement on installing all the things.

**Comment by StevenMaude** [comment]
![gitpod-font-display-bug](https://user-images.githubusercontent.com/3818079/121572732-65c16400-ca1c-11eb-9d84-3bf2bb8ee869.png)
This could be confusing, because we ask people to type `run_all`.

**Comment by StevenMaude** [comment]
https://community.gitpod.io/t/no-open-preview-icon-for-html-files/3764/3 links to https://github.com/gitpod-io/gitpod/issues/3831 which suggests using an extension.

My quick suggestion was run: `python3 -m http.server` in a terminal.

**Comment by StevenMaude** [comment]
We're not using Gitpod now, so this issue can be closed.

We might want to do a similar process of polishing up Codespaces to make that easier to use, but that should be in response to review of how Codespaces work, and feedback from users.
