### ISSUE TITLE
flake8 linting-induced confusion

### ISSUE THREAD

**Issue by Jongmassey** [opensafely/research-template#52]
I've had a couple of instances where flake8 linting has caused confusion with researchers I've been co-piloting who are not familiar with Python and are using VS code for the first time. It's particularly prevalent when trying to debug a non-working study definition (despite the error output from `cohortextractor` via `opensafely run` ("does the red squiggly line mean that's where the problem is or is that something else?").

It's enabled via `.vscode/settings.json` in #35 and I generally think it's a good idea but it's default configuration is perhaps too strict for non-Python-developer researchers just looking to get a study definition working. I propose disabling/loosening constraints on some rules via the `"python.linting.flake8Args"` setting.

Some examples from a recent meeting/debugging session:
* "what does  `# NOQA` do?" - if the first line of our own example code has to have a linting-disabling hint then that's not a great sign
* line length: many of the code snippets in the documentation are over 80 chars ([example](https://docs.opensafely.org/study-def-codelists/#pulling-codelists-into-your-study-definition)) and so get flagged. [E501](https://www.flake8rules.com/rules/E501.html)
  * this could probably be extended to ~120 without issue?
* "double comment marks - why does this matter/is this a problem?" - [E266](https://www.flake8rules.com/rules/E266.html)
* Unexpected spaces around keyword / parameter equals [E251](https://www.flake8rules.com/rules/E251.html) - again, the examples in the documentation don't all conform to this and I see it as a point of style rather than a functional impediment to getting a working study definition. 

Although [we say that some knowledge of Python is useful](https://docs.opensafely.org/study-def/#what-is-a-study-definition) to write a study definition, I think expecting researchers to write code that fully conforms with (and understand) the standard flake8 ruleset is a bit of a big ask for a novice Python user.

Additional to this, are we expecting researchers to blacken their python code? If so, the out-of-the-box behaviour of black still results in some flake8 warnings (e.g. 88 vs 79 char lines).

**Comment by StevenMaude** [comment]
Fixed by #119 — we've removed these settings.
