### ISSUE TITLE
Setup workflow

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/research-template#62]
If users copy-and-paste `.github/workflows/setup.yaml` from this repo to their study, then their study may fail with a hard-to-understand error. For example, [here][1] the setup workflow is trying to commit changes to `main`, but `main` is a protected branch.

The setup workflow is valuable when this repo is used as a template; it's less valuable when it's used as a place from which useful code can be copied-and-pasted into another study. Could we:

- Warn users about copying-and-pasting the setup workflow?
- Improve the setup workflow?
- Something else?

Thanks for [raising this issue][2], @milanwiedemann.

[1]: https://github.com/opensafely/qof-utilities/runs/6010323707?check_suite_focus=true
[2]: https://bennettoxford.slack.com/archives/C33TWNQ1J/p1649933587845879

**Comment by lucyb** [comment]
We should warn users not to copy and paste the setup workflow. Point to the documentation, so they use it as a template instead.

**Comment by bloodearnest** [comment]
Where should this warning go? Putting it the README feels wrong, as thats supposed to be the public face of the repo.

**Comment by ghickman** [comment]
While documentation is definitely good, there's the possibility of documenting things before they're a problem.  We don't want to dilute our docs with edge cases which rarely, if ever, happen.

A useful thing to ask ourselves here is "has an external researcher been caught out by this?" and base our decision on that.  Internal researchers, and congrats to @milanwiedemann for being what I think might be first on this particular error 😁, know more about how our system works.  That knowledge can lead to using tools in unexpected ways.

In this particular case I think it's most important to find out if this has come up before, and if not park/close/block this ticket until it's come up another couple of times to confirm it's not just a happy accident this time.

**Comment by sebbacon** [comment]
Definitely agree George. 

I wondered if a short comment _in the yaml_ is sufficient, without being over-the-top, though; thoughts?

**Comment by ghickman** [comment]
Yeah, a one-liner at the top, something like "this should only be included in repos generated from a template on GitHub".

**Comment by iaindillingham** [comment]
Would it be possible to have a more informative error message? So if you do copy-and-paste the study, and it does error, then the _Actions_ tab is more informative.

**Comment by ghickman** [comment]
Maybe, but my argument here is essentially "is it worth it?".  Does the screw driver packaging warn against using the handle as a hammer? (ok not a great argument because that obviously works 😂)

My feeling is, at this point where it's only happened once, probably not.  If it happens another couple of times then it's probably worth the time cost.

**Comment by sebbacon** [comment]
We have obviously wasted far too much time on this already.... but just for the sheer joy of keeping the conversation going, the alternate view is that it cost someone a lot of time working out what happened, and the comment would prevent that happening again, however unlikely it is.

I strongly agree with your argument it it related to user documentation, but I'm less convinced if we're just talking about a comment. We actively litter our code liberally with probably-never-again-relevant comments.

Anyway `wontfix` this already, I don't really care :laughing:

**Comment by ghickman** [comment]
> just for the sheer joy of keeping the conversation going

Just one more thing 😜

**Comment by sebbacon** [comment]
and another one

**Comment by bloodearnest** [comment]
Closing as won't fix as per the exciting discussion above.
